# Setup
title:               Home
tagline:             Home Page
url:                 http://Chobito.github.io
github_username:  chobito
disqus:              chobito # get it on https://disqus.com/admin/

# About/contact
author:
 name:                Pedro Romero Aguado
 email:               "pedroromeroaguado@gmail.com" # email here 
 profile-pic:         img/profile-pic.jpg
 url:            	 www.google.es
 facebook:          j4m3lg0
 twitter:           chobito90
 google_plus:       username
 linkedin:          promero


# Build settings
markdown:            kramdown
permalink:           /:title
sass:
  sass_dir:          _sass
  style:            :compressed


# Default settings
defaults:
  -
    scope:
      path: "" 
      type: "posts" 
    values:
      layout: "post"
      author: Pedro Romero
  -
    scope:
      path: "" 
      type: "pages" 
    values:
      layout: "page"
gems:
  - jemoji      
